import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SimpleSlider from '../components/SimpleSlider'
import About from '../components/About'
import Cta from '../components/Cta'
import CommunitySection from '../components/CommunitySection'
import SubscribeSection from '../components/SubscribeSection'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SimpleSlider />

      <About/>
      <Cta />
      <CommunitySection />
      <SubscribeSection />
    </div>
  )
}
